version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-app-node
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app
    #   - node_modules:/app/node_modules
    command: ["node", "dist/app/index.js"]
# volumes:
#   node_modules:
